elements = {
 # GHA ES
 "xp_search_bar": "//input[@role='combobox']",
 "xp_complementary_results": "//div[@class='xpdopen']",
 "xp_hotel_name": "//div/h2[@data-attrid='title']",
 "xp_date_home_page": "//div[@data-async-type='updateHotelBookingModule']//date-picker-immersive//a[@role='button']",
 "xp_start_date_gp_es_search_page": "//div[@data-async-type='updateHotelBookingModule']//a[@data-hdp-title='Llegada:']",
 "xp_start_date_gp_es": "//div[contains(@aria-label,'Select check-in date.')]",
 "xp_end_date_gp": "//div[contains(@aria-label,'Selecciona la fecha de salida.')]",
 "xp_end_date_gp_es_search_page": "//div[@data-async-type='updateHotelBookingModule']//a[@data-hdp-title='Salida:']",
 "xp_passenger_count_gp_1": "//div[contains(@class,'__date-picker')]/following-sibling::div[1]",
 "xp_passenger_count_gp_es": "//div[contains(@aria-label,'Set number of guests.')]",
 "xp_arrows_gp": "//two-month-calendar//calendar-flippers//div",
 "xp_more_options_es": "//span[contains(text(), 'View more rates')]",
 "xp_ads_list": "//span[@id='prices']//c-wiz[@class='rGDr8b']//span[@class='g32BKd ogfYpf zUyrwb']",
 "xp_month_header": "//div[@role='dialog']//div[@role='listitem']/div[1]",
 "xp_month_header_search_page": "//month-header//jsl",
 "xp_next_month_arrow": "//div[@role='dialog']//button[@aria-label='Next']",
 "xp_month_arrow": "//calendar-flippers//div",
 "cls_previous_month": "hudp-previousMonth",
 "xp_dates_search_page": "//calendar-day[@role='gridcell button']",
 "xp_loading_indicator_gp": "//div[contains(@class,'linear-indicator')]",
 "xp_ads_gp_progress_bar": "//div[@role='progressbar']",
 "xp_passenger_drop_down_es": "//div[contains(@aria-label,'Indica el número de huéspedes.')]//div[contains(@jsname,'wQNmvb')][@role='option'][contains(@aria-label,'huésped')][@aria-hidden='false'][@tabindex='-1']",

 # IBE ES
 "xp_date_selection_ibe": "//button[contains(@data-qa,'date_selection_button_open')]",
 "xp_tab_selection_ibe": "//h2[contains(text(),'Reservar Una Habitación')]",
 "xp_passenger_count_ibe": "//button[contains(@data-qa,'guest_selection_button_open')]",
 "xp_passenger_options": "//div[@jsaction='fire.occupancyItemSelect;touchend:fire.occupancyItemSelect']",
 "xp_date_ok_button_es": "//div[@role='dialog']/div[4]//span[contains(text(),'Done')]",

 # Trivago ES
 "xp_hotel_name_search_bar_trivago": "//input[@id='querytext']",
  "cls_hotel_name_suggestion": "ssg-title",
 "xp_checkin_date_tivago": "//button[@key='checkInButton']",
 "xp_month_header_trivago": "//th[@class='cal-heading-month']//span",
 "cls_next_button_tri": "cal-btn-next",
 "cls_trivago_dates": "cal-day-wrap",
 "xp_checkout_date": "//button[@key='checkOutButton']",
 "xp_passenger_trivago": "//button[contains(@class,'dealform-button dealform-button--guests')]",
 "xp_adult_drp_down_tri": "//select[contains(@id,'select-num-adults')]",
 "xp_child_drp_down_tri": "//select[contains(@id,'select-num-children')]",
 "xp_search_button_tivago": "//span[@class='search-button__label']",
 "xp_hotel_list_for_search_tivago": "//li[@class='hotel-item item-order__list-item js_co_item']",
 "xp_hotel_name_trivago": "//span[@data-qa='item-name']",
 "xp_cheap_deal_btn_tivago": "//button[contains(@class,'accommodation-list__button') and contains(@data-qa,'cheapest-deal')]",
 "xp_offers_header_trivago": "//h3[contains(@class,'slideouts__title')]",
 "xp_logo_for_offers_tivago": "//li[contains(@class,'slideout-deals__item--grouped')]//img",
 "xp_offer_sel_btn_tivago": "//li[contains(@class,'slideout-deals__item--grouped')]/div[contains(@class,' js_co_link')]//button",
 "xp_age_confirmation_btn_tri": "//button[contains(@class,'tertiary fl-trailing confirm')]",
 "xp_loading_indicator_trivago": "//section[@id='js_item_list_section']//div[contains(@class,'ellipsis-loader-wrapper')]",
 "xp_more_options_trivago": "//button[contains(@class,'pointer td-underline--hover')]",

 #GHA PT
 "xp_search_bar_pt": "//input[@role='combobox']",
 "xp_complementary_results_pt": "//div[@class='xpdopen']",
 "xp_hotel_name_pt": "//div/h2[@data-attrid='title']",
 "xp_start_date_gp_pt": "//div[contains(@aria-label,'data do check-in.')]",
 "xp_end_date_gp_pt": "//div[contains(@aria-label,'data do check-out.')]",
 "xp_passenger_count_gp_pt": "//div[contains(@aria-label,'Defina número de convidados.')]",
 "xp_arrows_gp": "//two-month-calendar//calendar-flippers//div",
 "xp_more_options_pt": "//span[contains(text(), 'Ver mais tarifas')]",
 "xp_ads_list": "//span[@id='prices']//c-wiz[@class='rGDr8b']//span[@class='g32BKd ogfYpf zUyrwb']",
 "xp_month_header": "//div[@role='dialog']//div[@role='listitem']/div[1]",
 "xp_month_header_1": "//div[@class='hudp']//td[@class='hudp-monthyear']",
 "cls_next_month": "hudp-nextMonth",
 "cls_previous_month": "hudp-previousMonth",
 "xp_date": "//th[@role='rowheader']/following-sibling::td[contains(@class,'hudp-date')]",
 "xp_loading_indicator_gp": "//div[contains(@class,'linear-indicator')]",
 "xp_ads_gp_progress_bar": "//div[@role='progressbar']",
 "xp_date_ok_button_pt": "//div[@role='dialog']/div[4]//span[contains(text(),'Concluído')]",
 "xp_passenger_drop_down_pt": "//div[contains(@aria-label,'Defina número de convidados.')]//div[contains(@jsname,'wQNmvb')][@role='option'][contains(@aria-label,'hóspede')][@aria-hidden='false'][@tabindex='-1']"
}
